export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const CREATE_TEAM = 'CREATE_TEAM';
export const CREATE_TEAM_SUCCESS= 'CREATE_TEAM_SUCCESS';
export const CREATE_TEAM_FAIL = 'CREATE_TEAM_FAIL';
export const END_CREATE_TEAM = 'END_CREATE_TEAM';

export const GENERATE_PLAYER = 'GENERATE_PLAYER';
export const GENERATE_PLAYER_SUCCESS = 'GENERATE_PLAYER_SUCCESS';
export const GENERATE_PLAYER_FAIL = 'GENERATE_PLAYER_FAIL';

export const SET_TEAMS = 'SET_TEAMS';
export const SET_GENERATED_PLAYERS = 'SET_GENERATED_PLAYERS';

// team players
export const FETCH_PLAYERS = 'FETCH_PLAYERS';
export const FETCH_PLAYERS_SUCCESS = 'FETCH_PLAYERS_SUCCESS';
export const FETCH_PLAYERS_FAIL = 'FETCH_PLAYERS_FAIL';

// standings
export const LOAD_TEAM_STANDINGS = 'LOAD_TEAM_STANDINGS';
export const LOAD_TEAM_STANDINGS_SUCCESS = 'LOAD_TEAM_STANDINGS_SUCCESS';
export const LOAD_TEAM_STANDINGS_FAIL = 'LOAD_TEAM_STANDINGS_FAIL';

// New Team Actions
export const ADD_PLAYER_NEW_TEAM = 'ADD_PLAYER_NEW_TEAM';
export const REMOVE_PLAYER_NEW_TEAM = 'REMOVE_PLAYER_NEW_TEAM';
