export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const CREATE_TEAM = 'CREATE_TEAM';
export const CREATE_TEAM_SUCCESS= 'CREATE_TEAM_SUCCESS';
export const CREATE_TEAM_FAIL = 'CREATE_TEAM_FAIL';
export const END_CREATE_TEAM = 'END_CREATE_TEAM';

export const GENERATE_PLAYER = 'GENERATE_PLAYER';
export const GENERATE_PLAYER_SUCCESS = 'GENERATE_PLAYER_SUCCESS';
export const GENERATE_PLAYER_FAIL = 'GENERATE_PLAYER_FAIL';

export const SET_TEAMS = 'SET_TEAMS';
export const SET_GENERATED_PLAYERS = 'SET_GENERATED_PLAYERS';

// team info
export const FETCH_TEAM = 'FETCH_TEAM';
export const FETCH_TEAM_SUCCESS = 'FETCH_TEAM_SUCCESS';
export const FETCH_TEAM_FAIL = 'FETCH_TEAM_FAIL';
export const FETCH_TEAM_PLAYERS_SUCCESS = 'FETCH_TEAM_PLAYERS_SUCCESS';
export const FETCH_TEAM_PLAYERS_FAIL = 'FETCH_TEAM_PLAYERS_FAIL';
export const LOAD_TEAM_GAMES_SUCCESS = 'LOAD_TEAM_GAMES_SUCCESS';
export const LOAD_TEAM_GAMES_FAIL = 'LOAD_TEAM_GAMES_FAIL'

// team players
export const FETCH_PLAYERS = 'FETCH_PLAYERS';
export const FETCH_PLAYERS_SUCCESS = 'FETCH_PLAYERS_SUCCESS';
export const FETCH_PLAYERS_FAIL = 'FETCH_PLAYERS_FAIL';

// standings
export const LOAD_TEAM_STANDINGS = 'LOAD_TEAM_STANDINGS';
export const LOAD_TEAM_STANDINGS_SUCCESS = 'LOAD_TEAM_STANDINGS_SUCCESS';
export const LOAD_TEAM_STANDINGS_FAIL = 'LOAD_TEAM_STANDINGS_FAIL';

// New Team Actions
export const GET_GENERATED_PLAYERS = 'GET_GENERATED_PLAYERS';
export const GET_GENERATED_PLAYERS_SUCCESS = 'GET_GENERATED_PLAYERS_SUCCESS';
export const ADD_PLAYER_NEW_TEAM = 'ADD_PLAYER_NEW_TEAM';
export const REMOVE_PLAYER_NEW_TEAM = 'REMOVE_PLAYER_NEW_TEAM';

// Report
export const FETCH_REPORT_SUCCESS = 'FETCH_REPORT_SUCCESS';
export const FETCH_REPORT_FAIL = 'FETCH_REPORT_FAIL';

// Game
export const FETCH_GAMES = 'FETCH_GAMES';
export const FETCH_GAMES_SUCCESS = 'FETCH_GAMES_SUCCESS';
export const FETCH_GAME = 'FETCH_GAME';
export const FETCH_GAME_SUCCESS = 'FETCH_GAME_SUCCESS';
export const CREATE_GAME = 'CREATE_GAME';
export const CREATE_GAME_SUCCESS = 'CREATE_GAME_SUCCESS';
export const SIMULATE_GAME = 'SIMULATE_GAME';
export const SIMULATE_GAME_SUCCESS = 'SIMULATE_GAME_SUCCESS';
export const SIMULATE_GAME_FAIL = 'SIMULATE_GAME_FAIL';
